application: ojournalclub
version: 1
runtime: python
api_version: 1

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: thegrandlocus_theme/static/images/favicon.ico
  upload: thegrandlocus_theme/static/images/favicon.ico

- url: /thegrandlocus_theme/static
  static_dir: thegrandlocus_theme/static

- url: /threads/.*
  script: thread_serve.py
  login: required

- url: /signin.html
  script: hard_html_serve.py
  login: required

- url: /newuser
  script: thread_serve.py
  login: required

- url: /.*
  script: hard_html_serve.py
